### ISSUE TITLE
训练 winrate 不变的的问题

### ISSUE THREAD

**Issue by rubbyzhang** [RuBP17/AlphaDou#5]
![3230857f869b0c1619eb600a0312ccdb](https://github.com/user-attachments/assets/560c0b82-ec0a-4efc-8e3f-524afeff5432)

我在训练的时候只是增加了actor数量，这个结果有点诡异，请教下是参数问题嘛？

**Comment by RuBP17** [comment]
Which agent you used to test your bots? If you use strong agents like douzero_resnet as opponents, your AI seems too weak to win. I started testing my bots when they learned about 1M frames, so I don't know whether there's a bug or just your bots are too weak.

**Comment by EvelynCarter** [comment]
> 如果使用douzero_resnet作为测试的对手的话，你的AI可能太弱了。我在100w帧之后才开始测试AI，所以我不知道这是一个bug，还是单纯是训练量太少了。
> 
> Which agent you used to test your bots? If you use strong agents like douzero_resnet as opponents, your AI seems too weak to win. I started testing my bots when they learned about 1M frames, so I don't know whether there's a bug or just your bots are too weak.

请问一下 4090开了多少actor bize 是30嘛

**Comment by rubbyzhang** [comment]
> 如果使用douzero_resnet作为测试的对手的话，你的AI可能太弱了。我在100w帧之后才开始测试AI，所以我不知道这是一个bug，还是单纯是训练量太少了。
> 
> Which agent you used to test your bots? If you use strong agents like douzero_resnet as opponents, your AI seems too weak to win. I started testing my bots when they learned about 1M frames, so I don't know whether there's a bug or just your bots are too weak.

**Comment by kid742** [comment]
你如果每次都用同样的小量评估数据，好像是会出现这样的情况，最好每次都重新生成一下
