### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED 

### ISSUE THREAD

**Issue by rubbyzhang** [RuBP17/AlphaDou#6]
/root/miniconda3/envs/alphadou/lib/python3.12/site-packages/torch/nn/modules/conv.py:306: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at /opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv1d(input, weight, bias, self.stride,    

ubantu22.04 系统，4090D， 驱动550.67
pytorch 版本  2.3
cuda版本12.1  cuDNN8.9 . 会出现这个问题，后来尝试过 2.1 + 11.8 /12.1  依然存在这个问题，请教下解决思路

**Comment by RuBP17** [comment]
There may be a mismatch between the version of cuDNN and the version of cuda/pytorch.
