### ISSUE TITLE
 [BUG] Possible Weight Loss When Resuming Training with Local Checkpoints

### ISSUE THREAD

**Issue by RuBP17** [RuBP17/AlphaDou#9]
Description:
When loading local checkpoint files to resume training, some weights may not load correctly. This issue might lead to degraded model performance or failure to achieve the expected results. It is currently recommended to avoid interrupting training and to continue training the model until convergence.

Expected Behavior:
After loading local checkpoints, all model weights should be correctly restored, allowing training to resume seamlessly.

Possible Causes:
Bugs in multiprocess training frame.

Workaround:
Avoid interrupting training whenever possible and continue until the model converges.

**Comment by EvelynCarter** [comment]
能否告知训练参数，使能够训练到模型收敛，之前的策略是不断调整参数，如果调整参数的话，不就要停止训练了吗？
Can you please provide the training parameters so that the model can converge during training? The previous strategy was to continuously adjust the parameters, but if we do, wouldn't we have to stop training？

**Comment by 0099az** [comment]
> 能否提供近期训练参数，使得能够训练到模型训练收敛，之前的策略是不断调整参数，如果调整参数的话，不是就要停止了吗？ 能否请您提供一下训练参数，以便模型在训练时能够收敛？之前的策略是不断调整参数，但是如果这样的话，不是就得停止训练了吗？

可以私聊我吗？有个问题想请你有偿解决
